<?php /** @var \Magento\Backend\Block\Template $block */ 
    $enableAutocompete = \Dfe\BackendLoginAutocomplete\Settings::s()->enable(); /** @var bool $enableAutocompete */
?>
<form method="post" action="" id="login-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?= __('Welcome, please sign in') ?></span>
        </legend><br/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>" />
        <div class="admin__field _required field-username">
            <label for="username" class="admin__field-label">
                <span><?= __('Username') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="username"
					class="admin__control-text"
					type="text"
					name="login[username]"
					autofocus
					value=""
					data-validate="{required:true}"
					placeholder="<?= __('user name') ?>"
					autocomplete="<?= ($enableAutocompete ? "username" : "off"); ?>"
				/>
            </div>
        </div>
        <div class="admin__field _required field-password">
            <label for="login" class="admin__field-label">
                <span><?= __('Password') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="login"
					class="admin__control-text"
					type="password"
					name="login[password]"
					data-validate="{required:true}"
					value=""
					placeholder="<?= __('password') ?>"
					autocomplete="<?= ($enableAutocompete ? "current-password" : "off"); ?>"
				/>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info'); ?>
        <div class="form-actions">
            <?= $block->getChildHtml('form.buttons'); ?>
        </div>
    </fieldset>
</form>